<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-G6NDRKF" failures="1" tests="1" name="Default test(failed)" time="2.483" errors="0" timestamp="2024-04-03T12:01:20 CEST">
  <testcase classname="com.fithub.services.chat.test.suites.ChatroomServiceTest" name="testCreateNewChatroom_ValidDataProvided_ChatroomCreated" time="0.012">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at com.fithub.services.chat.test.suites.ChatroomServiceTest.testCreateNewChatroom_ValidDataProvided_ChatroomCreated(ChatroomServiceTest.java:118)
at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:154)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testCreateNewChatroom_ValidDataProvided_ChatroomCreated -->
  <testcase classname="com.fithub.services.chat.test.suites.ChatroomServiceTest" name="testCreateNewChatroom_InvalidDataIsProvided_ThrowsException" time="0.0">
    <ignored/>
  </testcase> <!-- testCreateNewChatroom_InvalidDataIsProvided_ThrowsException -->
</testsuite> <!-- Default test(failed) -->
